language: java

jdk:
  - openjdk14

sudo: false

env:
  global:
    - CODECOV_TOKEN="3e0665f7-7c59-49f6-ad63-2382c5f9e54d"


# Start PostgreSQL
services:
  - postgresql

# Create a database
before_script:
  - psql -c 'create database idea_db;' -U postgres

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      -sgt16@yandex.ru
    on_success: never # default: change
    on_failure: always # default: always
